# 가장 최근 날짜 출력하기
SELECT NAME FROM ANIMAL_INS ORDER BY DATETIME DESC LIMIT 10

# 개수 세기
SELECT Count(ANIMAL_ID) AS 'count' FROM ANIMAL_INS

# 중복 제거하고 개수 세기
SELECT Count(DISTINCT NAME) FROM ANIMAL_INS

# NULL 값을 0으로 계산하기
SELECT COUNT(IFNULL(COLUMN_NAME,0)) FROM TABLE_NAME

# 고양이와 강아지가 각각 몇마리인지 계산하기
SELECT ANIMAL_TYPE, COUNT(*) FROM ANIMAL_INS GROUP BY ANIMAL_TYPE ORDER BY ANIMAL_TYPE ASC
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE IN ("Dog", "Cat")) FROM ANIMAL_INS GROUP BY ANIMAL_TYPE ORDER BY ANIMAL_TYPE ASC

# 중복되는 이름과 개수 조회
SELECT NAME, COUNT(NAME) FROM ANIMAL_INS GROUP BY NAME HAVING COUNT(NAME) > 1 ORDER BY NAME

# 09:00 ~ 19:59 사이의 시간 개수 세기
SELECT HOUR(DATETIME) AS hour, COUNT(HOUR(DATETIME)) as count 
FROM ANIMAL_OUTS 
WHERE DATE_FORMAT(datetime, '%H:%I') BETWEEN '09:00' AND '19:59'
GROUP BY hour
ORDER BY hour ASC

# 임시 테이블 만든 후 LEFT JOIN으로 합치기
WITH RECURSIVE TIMETABLE(HOUR) AS (
    SELECT 0
    UNION
    SELECT TIMETABLE.HOUR + 1 FROM TIMETABLE WHERE TIMETABLE.HOUR < 23
)
SELECT HOUR, COUNT(ANIMAL_OUTS.DATETIME) FROM TIMETABLE
LEFT JOIN ANIMAL_OUTS ON TIMETABLE.HOUR = HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY HOUR
ORDER BY HOUR