# A 테이블과 B 테이블 중 A 테이블에 없는 ID를 조회 : LEFT OUTER JOIN
# LEFT OUTER JOIN : JOIN 기준 왼쪽에 있는 것만! 차집합

SELECT O.ANIMAL_ID, O.NAME FROM ANIMAL_OUTS AS O LEFT OUTER JOIN ANIMAL_INS AS I
ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE I.ANIMAL_ID IS NULL
ORDER BY O.ANIMAL_ID

# LEFT INNER JOIN : A와 B의 교집합
SELECT ON A.ID, A.NAME, A.DATETIME
FROM A
INNER JOIN B
ON A.ID = B.ID 

# LEFT JOIN : JOIN 기준 왼쪽에 있는 것을 전부 기준으로(공통부분 + A)
SELECT ON A.ID, A.NAME, A.DATETIME
FROM A 
LEFT OUTER JOIN B
ON A.ID = B.ID

# 참고 : https://pearlluck.tistory.com/46

# 두 테이블을 비교하여 A의 값이 더 작은 데이터 추출
SELECT I.ANIMAL_ID, I.NAME FROM ANIMAL_INS AS I
INNER JOIN ANIMAL_OUTS AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.DATETIME > O.DATETIME
ORDER BY I.DATETIME

# 두 테이블을 비교하여 B테이블에 없는 값을 가진 A 테이블 데이터 중 TOP 3 조회
SELECT I.NAME, I.DATETIME FROM ANIMAL_INS AS I
LEFT OUTER JOIN ANIMAL_OUTS AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE O.ANIMAL_ID IS NULL
ORDER BY I.DATETIME
LIMIT 3

# 외부 키 이용하기
SELECT NAME, DATETIME FROM ANIMAL_INS 
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS) 
ORDER BY DATETIME
LIMIT 3

# 두 테이블의 특정 컬럼값이 다른 경우 출력하기
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME FROM ANIMAL_INS AS I
INNER JOIN ANIMAL_OUTS AS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE != O.SEX_UPON_OUTCOME

# 특정 값이 포함되지 않는 경우 출력하기
SELECT I.ANIMAL_ID, I.ANIMAL_TYPE, I.NAME FROM ANIMAL_INS AS I
INNER JOIN ANIMAL_OUTS AS O 
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE I.SEX_UPON_INTAKE LIKE '%Intact%' AND O.SEX_UPON_OUTCOME NOT LIKE '%Intact%'
ORDER BY I.ANIMAL_ID
